/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyingRouteImport } from './routes/buying'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpecialsRouteImport } from './routes/specials'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StoryRouteImport } from './routes/story'
import { Route as WasteRouteImport } from './routes/waste'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyingRoute = BuyingRouteImport.update({
  id: '/buying',
  path: '/buying',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialsRoute = SpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const WasteRoute = WasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buying': typeof BuyingRoute
  '/forecast': typeof ForecastRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/specials': typeof SpecialsRoute
  '/stock': typeof StockRoute
  '/story': typeof StoryRoute
  '/waste': typeof WasteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buying': typeof BuyingRoute
  '/forecast': typeof ForecastRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/specials': typeof SpecialsRoute
  '/stock': typeof StockRoute
  '/story': typeof StoryRoute
  '/waste': typeof WasteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buying': typeof BuyingRoute
  '/forecast': typeof ForecastRoute
  '/insights': typeof InsightsRoute
  '/settings': typeof SettingsRoute
  '/specials': typeof SpecialsRoute
  '/stock': typeof StockRoute
  '/story': typeof StoryRoute
  '/waste': typeof WasteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buying'
    | '/forecast'
    | '/insights'
    | '/settings'
    | '/specials'
    | '/stock'
    | '/story'
    | '/waste'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buying'
    | '/forecast'
    | '/insights'
    | '/settings'
    | '/specials'
    | '/stock'
    | '/story'
    | '/waste'
  id:
    | '__root__'
    | '/'
    | '/buying'
    | '/forecast'
    | '/insights'
    | '/settings'
    | '/specials'
    | '/stock'
    | '/story'
    | '/waste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyingRoute: typeof BuyingRoute
  ForecastRoute: typeof ForecastRoute
  InsightsRoute: typeof InsightsRoute
  SettingsRoute: typeof SettingsRoute
  SpecialsRoute: typeof SpecialsRoute
  StockRoute: typeof StockRoute
  StoryRoute: typeof StoryRoute
  WasteRoute: typeof WasteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buying': {
      id: '/buying'
      path: '/buying'
      fullPath: '/buying'
      preLoaderRoute: typeof BuyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specials': {
      id: '/specials'
      path: '/specials'
      fullPath: '/specials'
      preLoaderRoute: typeof SpecialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waste': {
      id: '/waste'
      path: '/waste'
      fullPath: '/waste'
      preLoaderRoute: typeof WasteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyingRoute: BuyingRoute,
  ForecastRoute: ForecastRoute,
  InsightsRoute: InsightsRoute,
  SettingsRoute: SettingsRoute,
  SpecialsRoute: SpecialsRoute,
  StockRoute: StockRoute,
  StoryRoute: StoryRoute,
  WasteRoute: WasteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
